### ISSUE TITLE
RegisterDirty not work

### ISSUE THREAD

**Issue by tungh1** [SDolha/UnitOfWork-EntityFramework#4]
Dear SDolha

I used your framework update function using RegisterDirty not work. When updating the db is addnew.
Thanks, 
Tung Hoang

**Comment by sorin-ref** [comment]
Register* methods for the Entity Framework (EF) implementation of IUnityOfWork do nothing, i.e. they do not need to do anything – see source code at https://github.com/SDolha/UnitOfWork-EntityFramework/blob/master/UnitOfWorkEntityFramework/DataAccessPatterns.EntityFramework/UnitOfWork.cs

The reason is that EF itself, for a DbContext, holds state of entities itself, and when calling SaveChanges that state is used.

Register* methods are provided, though, because not always the underlying frameworks (that may also provide repositories) record state about the entities. So here I just tried to combine theory with practice, i.e. to be able to work with theoretical way, without thinking about EF (although EF would do the job itself) and then you could switch from EF to a different “platform” regardless of whether it provides the same features or not, just by implementing the missing things in a custom IUnitOfWork implementation.

Note also that I have an example of applying changes both using new rows and using already existing database rows in the usage sample code at https://github.com/SDolha/UnitOfWork-EntityFramework/blob/master/UnitOfWorkEntityFramework/SampleApp.UserInterface/Program.cs
